version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date