version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
        environment:
          DOCKER_BUILDKIT: '1'
        
    working_directory: ~/repo/src

    steps:
      - checkout:
          path: ~/repo
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: false

      - run:
          name: Build a container
          command: |
            docker build -t app-ci/build -f Dockerfile . --target build