version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
        environment:
          DOCKER_BUILDKIT: '1'
        
    working_directory: ~/repo/src

    steps:
      - checkout:
          path: ~/repo
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: false

      - run:
          name: Build app
          command: |
            docker build -t app-ci/build -f Dockerfile . --target build

      - run:
          name: Test app
          command: |
            docker build -t app-ci/test -f Dockerfile . --target test

      - run:
          name: Extract test result
          when: always
          command: |
            docker cp $(docker create --rm app-ci/test):/artifacts ~/tests

      - store_test_results:
          name: Store tests results
          path: ~/tests
      - store_artifacts:
          name: Store artifact
          path: ~/tests